### ISSUE TITLE
authentication error with edugain

### ISSUE THREAD

**Issue by andreacorleto** [teltek/PuMuKIT2-up2u-pr-bundle#13]
I got an error while authenticating into poddium.eu with edugain. Attached picture with the error reported
![poddium-erroer-authentication](https://user-images.githubusercontent.com/36439670/51021394-b4cfea00-1581-11e9-8735-55db7803d85f.jpg)

**Comment by rubenrua** [comment]
Log:
```
[2018-12-12 10:48:04] security.ERROR: The status code of the Response was not Success, was Responder -> SimpleSAML_Error_Exception: GWDG\AccountManager\Exceptions\AdapterException: GWDG\AccountManager\Exceptions\UniqueConstraintException in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:132 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:152 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} [] []
[2018-12-12 10:52:23] security.ERROR: The status code of the Response was not Success, was Responder -> SimpleSAML_Error_Exception: GWDG\AccountManager\Exceptions\AdapterException: GWDG\AccountManager\Exceptions\UniqueConstraintException in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:132 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:152 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} [] []
[2018-12-12 11:01:25] security.ERROR: The status code of the Response was not Success, was Responder -> SimpleSAML_Error_Exception: GWDG\AccountManager\Exceptions\AdapterException: GWDG\AccountManager\Exceptions\UniqueConstraintException in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:132 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:152 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} [] []
[2018-12-12 11:05:03] security.ERROR: The status code of the Response was not Success, was Responder -> SimpleSAML_Error_Exception: GWDG\AccountManager\Exceptions\AdapterException: GWDG\AccountManager\Exceptions\UniqueConstraintException in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:132 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} in /var/simplesamlphp/vendor/gwdg/account-manager/src/MidPointAccountManager.php:152 Stack trace: #0 /var/simplesamlphp/modules/serviceaccount/lib/Auth/Process/ServiceAccount.php(107): GWDG\AccountManager\MidPointAccountManager->findAccount(Array) #1 /var/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php(195): sspmod_serviceaccount_Auth_Process_ServiceAccount->process(Array) #2 /var/simplesamlphp/lib/SimpleSAML/IdP.php(331): SimpleSAML_Auth_ProcessingChain->processState(Array) #3 /var/simplesamlphp/lib/SimpleSAML/IdP.php(417): SimpleSAML_IdP::postAuth(Array) #4 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php(431): SimpleSAML_IdP->handleAuthenticationRequest(Array) #5 /var/simplesamlphp/www/saml2/idp/SSOService.php(19): sspmod_saml_IdP_SAML2::receiveAuthnRequest(Object(SimpleSAML_IdP)) #6 {main} [] []
```

**Comment by andreacorleto** [comment]
This issue still pending but we should fix it before Pilot launch. Any update?

**Comment by Alfro** [comment]
@andreacorleto We are contacting the people managing the Up2U SSO as we can't log in with our eduGAIN accounts at all. We will report as soon as there's progress.

**Comment by Alfro** [comment]
Hello @andreacorleto, could you please try again to log to **both** of these platforms?

https://poddium.eu
https://pre-pr-up2u.teltek.es

Thanks,

**Comment by andreacorleto** [comment]
Hi  @Alfro, edugain authentication is working fine on https://pre-pr-up2u.teltek.es but still doesn't work on https://poddium.eu. I got the same error reported above.

**Comment by Alfro** [comment]
Hi @andreacorleto Could you try accessing poddium.eu again? We think we may have found the issue with your account.

**Comment by andreacorleto** [comment]
Hi @Alfro, now authentication with edugain it's fine. Thanks a lot for your great work!

**Comment by Alfro** [comment]
Thanks! I will close the issue then.
